// из 20 фильмов для интернет-кинотеатра

const movies = [
    {
        id: 1,
        title: "Дюна: Часть вторая",
        year: 2024,
        genre: "Фантастика",
        rating: 8.7,
        duration: "2 часа 46 мин",
        director: "Дени Вильнёв",
        description: "Пол Атрейдес объединяется с фрименами, чтобы отомстить заговорщикам, уничтожившим его семью. Его ждёт выбор между любовью и судьбой всей вселенной.",
        posterUrl: "img/dune.jpg",
        trailerUrl: "https://www.youtube.com/watch?v=Way9Dexny3w"
    },
    {
        id: 2,
        title: "Оппенгеймер",
        year: 2023,
        genre: "Драма",
        rating: 8.5,
        duration: "3 часа 0 мин",
        director: "Кристофер Нолан",
        description: "История создания атомной бомбы и её создателя — гениального физика Роберта Оппенгеймера, который сталкивается с моральными последствиями своего открытия.",
        posterUrl: "img/oppenheimer.jpg",
        trailerUrl: "https://www.youtube.com/watch?v=uYPbbksJxIg"
    },
    {
        id: 3,
        title: "Барби",
        year: 2023,
        genre: "Комедия",
        rating: 7.8,
        duration: "1 час 54 мин",
        director: "Грета Гервиг",
        description: "Барби и Кен отправляются в путешествие в реальный мир, где их ждут неожиданные открытия и приключения.",
        posterUrl: "img/barbie.jpg",
        trailerUrl: "https://www.youtube.com/watch?v=pBk4NYhWNMM"
    },
    {
        id: 4,
        title: "Джон Уик 4",
        year: 2023,
        genre: "Боевик",
        rating: 8.1,
        duration: "2 часа 49 мин",
        director: "Чад Стахелски",
        description: "Легендарный киллер продолжает борьбу с Правлением. Джон Уик находит способ обрести свободу, но цена может оказаться слишком высокой.",
        posterUrl: "img/john_wick.jpg",
        trailerUrl: "https://www.youtube.com/watch?v=yjRHZEUamCc"
    },
    {
        id: 5,
        title: "Стражи Галактики 3",
        year: 2023,
        genre: "Фантастика",
        rating: 8.0,
        duration: "2 часа 30 мин",
        director: "Джеймс Ганн",
        description: "Команда Стражей отправляется на спасение Ракеты. Финальная глава их приключений, полная юмора, экшна и неожиданных поворотов.",
        posterUrl: "img/guardians_of_the_galaxy.jpg",
        trailerUrl: "https://www.youtube.com/watch?v=u3V5KDHRQvk"
    },
    {
        id: 6,
        title: "Гарри Поттер и философский камень",
        year: 2001,
        genre: "Фантастика",
        rating: 8.2,
        duration: "2 часа 32 мин",
        director: "Крис Коламбус",
        description: "Мальчик-волшебник поступает в Хогвартс, где находит друзей, магию и сталкивается с тёмными силами.",
        posterUrl: "img/harry_potter.jpg",
        trailerUrl: "https://www.youtube.com/watch?v=VyHV0BRtdxo"
    },
    {
        id: 7,
        title: "Титаник",
        year: 1997,
        genre: "Драма",
        rating: 8.9,
        duration: "3 часа 14 мин",
        director: "Джеймс Кэмерон",
        description: "История любви на фоне катастрофы века. Джек и Роуз — два пассажира с разных социальных слоёв, чьи судьбы переплелись на легендарном лайнере.",
        posterUrl: "img/titanic.jpg",
        trailerUrl: "https://www.youtube.com/watch?v=kVrqfYjkTdQ"
    },
    {
        id: 8,
        title: "Начало",
        year: 2010,
        genre: "Фантастика",
        rating: 8.6,
        duration: "2 часа 28 мин",
        director: "Кристофер Нолан",
        description: "Кобб — вор, крадущий секреты из снов. Его последняя миссия — не украсть идею, а внедрить её. Это изменит реальность.",
        posterUrl: "img/inception.jpg",
        trailerUrl: "https://www.youtube.com/watch?v=YoHD9XEInc0"
    },
    {
        id: 9,
        title: "Зеленая книга",
        year: 2018,
        genre: "Драма",
        rating: 8.4,
        duration: "2 часа 10 мин",
        director: "Питер Фаррелли",
        description: "Итальянский вышибала нанимается водителем к темнокожему пианисту в турне по американскому Югу 1960-х. Основано на реальных событиях.",
        posterUrl: "img/green_book.jpg",
        trailerUrl: "https://www.youtube.com/watch?v=QyZKLX3b0l0"
    },
    {
        id: 10,
        title: "Джокер",
        year: 2019,
        genre: "Драма",
        rating: 8.7,
        duration: "2 часа 2 мин",
        director: "Тодд Филлипс",
        description: "История происхождения легендарного злодея Готэма — Артура Флека, неудачливого комика, чья жизнь рушится на глазах.",
        posterUrl: "img/joker.jpg",
        trailerUrl: "https://www.youtube.com/watch?v=t433PEQGErc"
    },
    {
        id: 11,
        title: "Паразиты",
        year: 2019,
        genre: "Триллер",
        rating: 8.5,
        duration: "2 часа 12 мин",
        director: "Пон Джун-хо",
        description: "Семья бедняков внедряется в дом богатых под видом сотрудников. Остросоциальный триллер с неожиданным финалом.",
        posterUrl: "img/parasite.jpg",
        trailerUrl: "https://www.youtube.com/watch?v=5xH0HfJHsaY"
    },
    {
        id: 12,
        title: "Форсаж 10",
        year: 2023,
        genre: "Боевик",
        rating: 7.2,
        duration: "2 часа 21 мин",
        director: "Луи Летерье",
        description: "Доминик Торетто и его команда сталкиваются с самым опасным врагом — сыном наркобарона, который жаждет мести.",
        posterUrl: "img/furious.jpg",
        trailerUrl: "https://www.youtube.com/watch?v=aOq49gW0iTs"
    },
    {
        id: 13,
        title: "Матрица: Воскрешение",
        year: 2021,
        genre: "Фантастика",
        rating: 6.8,
        duration: "2 часа 28 мин",
        director: "Лана Вачовски",
        description: "Нео и Тринити возвращаются в Матрицу. Сможет ли Нео снова стать Избранным в мире, где реальность и иллюзия переплелись?",
        posterUrl: "img/matrix.jpg",
        trailerUrl: "https://www.youtube.com/watch?v=9ix7TUGVYIo"
    },
    {
        id: 14,
        title: "Мстители: Финал",
        year: 2019,
        genre: "Фантастика",
        rating: 8.4,
        duration: "3 часа 1 мин",
        director: "Энтони и Джо Руссо",
        description: "Мстители собираются в последний раз, чтобы отменить действия Таноса и восстановить справедливость во вселенной.",
        posterUrl: "img/the_avengers.jpg",
        trailerUrl: "https://www.youtube.com/watch?v=TcMBFSGVi1c"
    },
    {
        id: 15,
        title: "Человек-паук: Через вселенные",
        year: 2018,
        genre: "Мультфильм",
        rating: 8.7,
        duration: "1 час 57 мин",
        director: "Боб Персикетти, Питер Рэмзи",
        description: "Майлз Моралес становится новым Человеком-пауком и встречает других пауков из параллельных вселенных.",
        posterUrl: "img/spider-man.jpeg",
        trailerUrl: "https://www.youtube.com/watch?v=lgZlh9cCZZ8"
    },
    {
        id: 16,
        title: "Бегущий по лезвию 2049",
        year: 2017,
        genre: "Фантастика",
        rating: 8.0,
        duration: "2 часа 44 мин",
        director: "Дени Вильнёв",
        description: "Новый репликант — охотник на репликантов находит секрет, который может погрузить общество в хаос.",
        posterUrl: "img/blade_runner.jpg",
        trailerUrl: "https://www.youtube.com/watch?v=gCcx85zbxz4"
    },
    {
        id: 17,
        title: "Криминальное чтиво",
        year: 1994,
        genre: "Криминал",
        rating: 8.9,
        duration: "2 часа 34 мин",
        director: "Квентин Тарантино",
        description: "Переплетающиеся истории гангстеров, боксёра и грабителей. Культовый фильм с незабываемыми диалогами.",
        posterUrl: "img/pulp_fiction.jpg",
        trailerUrl: "https://www.youtube.com/watch?v=s7EdQ4FqbhY"
    },
    {
        id: 18,
        title: "Дедпул 3",
        year: 2024,
        genre: "Комедия",
        rating: 8.3,
        duration: "2 часа 7 мин",
        director: "Шон Леви",
        description: "Дедпул объединяется с Росомахой в новом безумном приключении, ломая четвёртую стену как никогда раньше.",
        posterUrl: "img/deadpool.jpg",
        trailerUrl: "https://www.youtube.com/watch?v=ID7eC4CgH_U"
    },
    {
        id: 19,
        title: "Гладиатор",
        year: 2000,
        genre: "Боевик",
        rating: 8.5,
        duration: "2 часа 35 мин",
        director: "Ридли Скотт",
        description: "Римский генерал Максимус предан, бежит и становится гладиатором, чтобы отомстить коррумпированному императору.",
        posterUrl: "img/gladiator.jpg",
        trailerUrl: "https://www.youtube.com/watch?v=owK1qxDselE"
    },
    {
        id: 20,
        title: "Одержимость",
        year: 2014,
        genre: "Драма",
        rating: 8.5,
        duration: "1 час 47 мин",
        director: "Дэмьен Шазелл",
        description: "Молодой барабанщик стремится стать великим, но его преподаватель использует жесточайшие методы для воспитания гения.",
        posterUrl: "img/whiplash.jpg",
        trailerUrl: "https://www.youtube.com/watch?v=Q9PxDPOoZr4"
    }
];

console.log("✅ data.js загружен, фильмов:", movies.length);